Base/Controllers/HajjOfficeController.cs
using System;
using System.Linq.Expressions;
using System.Web.Mvc;
using Base.Model1;
using Base.Service.Interfaces;
using Base.Service.Services;

namespace Base.Controllers
{
    public class HajjOfficeController : BaseController
    {
        private readonly IHajjOfficeService _hajjOfficeService;
        private readonly IUserService _userService;
        private readonly IOfficeReqService _fficeReqService;
        private readonly IHajjReqService _hajjReqService;

        public HajjOfficeController(IHajjOfficeService hajjOfficeService, IUserService userService, IOfficeReqService fficeReqService, IHajjReqService hajjReqService)
        {
            _hajjOfficeService = hajjOfficeService;
            _userService = userService;
            _fficeReqService = fficeReqService;
            _hajjReqService = hajjReqService;
        }

        // GET: HajjOffice
        public ActionResult Index()
        {
            var hajjOffices = _hajjOfficeService.GetEntities();

            return View(hajjOffices);
        }



        // GET: HajjOffice/Details/5
        public ActionResult Details(int id)
        {
            var hajjOffice = _hajjOfficeService.GetEntity(id);
            if (hajjOffice == null)
            {
                return HttpNotFound();
            }
            return View(hajjOffice);
        }



        // GET: HajjOffice/Create
   
            public ActionResult Create()
            {
                ViewBag.RepresentativeList = new SelectList(_userService.GetEntities(), "ID", "Name");
                return View();
            }


        // POST: HajjOffice/Create
        [HttpPost]
        //[ValidateAntiForgeryToken]
        public ActionResult Create(HajjOffice hajjOffice)
        {
            if (ModelState.IsValid)
            {
                _hajjOfficeService.CreateEntity(hajjOffice);
                _hajjOfficeService.SaveEnitiy();
                return RedirectToAction("Index");
            }

            // In case of validation errors, repopulate the dropdown list with the selected value
            ViewBag.RepresentativeList = new SelectList(_userService.GetEntities(), "ID", "Name", hajjOffice.OfficeRepresentativeID);

            return View(hajjOffice);
        }

        [Route("Edit/{id}")]

        public ActionResult Edit(int id)
        {
            var hajjOffice = _hajjOfficeService.GetEntity(id);
            if (hajjOffice == null)
            {
                // Log the ID or perform other diagnostics
                return HttpNotFound();
            }
            ViewBag.RepresentativeList = new SelectList(_userService.GetEntities(), "ID", "Name", hajjOffice.OfficeRepresentativeID);
            return View(hajjOffice);
        }


        // GET: HajjOffice/Edit/5
        [HttpPost]
        public ActionResult Edit(HajjOffice hajjOffice)
        {
            if (ModelState.IsValid)
            {
                // Update and save the entity
                _hajjOfficeService.Update(hajjOffice);
                _hajjOfficeService.SaveEnitiy(); // Correct method name

                return RedirectToAction("Index");
            }

            // Repopulate the dropdown in case of validation failure
            ViewBag.RepresentativeList = new SelectList(_userService.GetEntities(), "ID", "Name", hajjOffice.OfficeRepresentativeID);

            return View(hajjOffice);
        }

        // GET: HajjOffice/Delete/5
        public ActionResult Delete(int id)
        {
            var hajjOffice = _hajjOfficeService.GetEntity(id);
            if (hajjOffice == null)
            {
                return HttpNotFound();
            }
            return View(hajjOffice);
        }

        // POST: HajjOffice/Delete/5
        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            var hajjOffice = _hajjOfficeService.GetEntity(id);
            if (hajjOffice != null)
            {
                _hajjOfficeService.Delete(hajjOffice);
            }

            return RedirectToAction("Index");
        }

        public ActionResult Search(string officeName)
        {
            Expression<Func<HajjOffice, bool>> condition = o => o.OfficeName.Contains(officeName);
            var filteredHajjOffices = _hajjOfficeService.Getmany(condition);

            return View("Index", filteredHajjOffices);
        }
        [HttpGet]
        public ActionResult CreateOfficeReq()
        {
            // Fetch the dropdown data for Hajj offices and requests
            ViewBag.HajjOffices = new SelectList(_hajjOfficeService.GetEntities(), "ID", "OfficeName");
            ViewBag.HajjRequests = new SelectList(_hajjReqService.GetEntities(), "ID", "Name");

            // Return the empty OfficeReq object to be filled in the form
            return PartialView("OfficeRequest", new OfficeReq());
        }

        [HttpPost]
        public ActionResult CreateOfficeReq(OfficeReq officeReq)
        {
            if (ModelState.IsValid)
            {
                _fficeReqService.CreateEntity(officeReq);  // Create the new OfficeReq
                _fficeReqService.SaveEnitiy();  // Save changes to the database
                return Json(new { success = true });  // Return success response
            }

            // Repopulate dropdowns for validation failure scenarios
            ViewBag.HajjRequests = new SelectList(_hajjReqService.GetEntities(), "ID", "Name");
            ViewBag.HajjOffices = new SelectList(_hajjOfficeService.GetEntities(), "ID", "OfficeName");

            // Return partial view with validation errors
            return PartialView("OfficeRequest", officeReq);
        }


        //[HttpPost]
        //public ActionResult CreateOfficeReq(OfficeReq officeReq)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        _fficeReqService.CreateEntity(officeReq); // Create the new OfficeReq
        //        _fficeReqService.SaveEnitiy(); // Save changes to the database

        //        // Return success as a JSON response (for AJAX submission)
        //        return Json(new { success = true });
        //    }

        //    // If ModelState is invalid, repopulate the dropdowns for the partial view
        //    ViewBag.HajjRequests = new SelectList(_hajjReqService.GetEntities(), "ID", "RequestName");
        //    ViewBag.HajjOffice = new SelectList(_hajjOfficeService.GetEntities(), "ID", "OfficeName");

        //    // Return partial view with validation errors (for AJAX submission)
        //    return PartialView("OfficeRequest", officeReq);
        //}


    }
}

Base/Views/HajjOffice/Create.cshtml
@model Base.Model1.HajjOffice

@{
    ViewBag.Title = "إنشاء مكتب خدمة";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<br/>
<br />
<br />
<br />
<br />
<div class="container mt-5">

    @using (Html.BeginForm())
    {
        <div class="card shadow-lg border-0">
            <div class="card-header bg-dark text-white">
                <h4 class="text-center">إضافة مكتب خدمة</h4>
            </div>
            <div class="card-body">
                <div class="form-group row">
                    @Html.LabelFor(model => model.OfficeName, "اسم المكتب", new { @class = "col-md-2 col-form-label text-right" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.OfficeName, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.OfficeName, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group row">
                    @Html.LabelFor(model => model.OfficePhone, "رقم الهاتف", new { @class = "col-md-2 col-form-label text-right" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.OfficePhone, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.OfficePhone, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group row">
                    @Html.LabelFor(model => model.OfficeRepresentativeID, "المسؤول", new { @class = "col-md-2 col-form-label text-right" })
                    <div class="col-md-10">
                        @Html.DropDownList("OfficeRepresentativeID", ViewBag.RepresentativeList as SelectList, "اختر", new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.OfficeRepresentativeID, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group row mt-4">
                    <div class="col-md-10 offset-md-2 text-right">
                        <input type="submit" value="حفظ" class="btn btn-success btn-lg px-5" />
                        @Html.ActionLink("العودة", "Index", null, new { @class = "btn btn-secondary btn-lg px-5 ml-3" })
                    </div>
                </div>
            </div>
        </div>
    }
</div>

Base/Views/HajjOffice/Delete.cshtml
@model Base.Model1.HajjOffice

@{
    ViewBag.Title = "حذف مكتب خدمة";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<br />
<br />
<br />
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card shadow-lg border-0">
                <div class="card-header bg-dark text-white">
                    <h4 class="text-center">تأكيد الحذف</h4>
                </div>
                <div class="card-body text-center">
                    <h5>هل أنت متأكد أنك تريد حذف هذا المكتب؟</h5>
                    <h5 class="text-danger mt-3">@Model.OfficeName</h5>
                </div>
                <div class="card-footer text-right">
                    <button id="deleteButton" class="btn btn-danger btn-lg px-4">حذف</button>
                    @Html.ActionLink("إلغاء", "Index", null, new { @class = "btn btn-secondary btn-lg px-4 ml-3" })
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script>
        document.getElementById('deleteButton').onclick = function (event) {
            event.preventDefault(); // Prevent the default action

            // SweetAlert2 confirmation dialog
            Swal.fire({
                title: 'هل أنت متأكد؟',
                text: "هذا سيؤدي إلى حذف المكتب بشكل دائم!",
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#d33',
                cancelButtonColor: '#3085d6',
                confirmButtonText: 'نعم، احذفها!',
                cancelButtonText: 'إلغاء'
            }).then((result) => {
                if (result.isConfirmed) {
                    // If confirmed, submit the form
                    const form = document.createElement('form');
                    form.method = 'post';
                    form.action = '@Url.Action("Delete", "HajjOffice")'; // Specify the action URL

                    const hiddenInput = document.createElement('input');
                    hiddenInput.type = 'hidden';
                    hiddenInput.name = 'id';
                    hiddenInput.value = '@Model.ID'; // Use the model ID

                    form.appendChild(hiddenInput);
                    document.body.appendChild(form);
                    form.submit();
                }
            });
        };
    </script>
}

Base/Views/HajjOffice/Details.cshtml
@model Base.Model1.HajjOffice

@{
    ViewBag.Title = "تفاصيل مكتب خدمة";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<br />
<br />
<br />
<br />
<br />
<div class="container mt-5">

    <div class="card shadow-lg border-0">
        <div class="card-header bg-dark text-white text-center">
            <h4>عرض مكتب الخدمة</h4>
        </div>
        <div class="card-body">
            <dl class="row">
                <dt class="col-md-3">أسم مكتب الخدمة</dt>
                <dd class="col-md-9">@Html.DisplayFor(model => model.OfficeName)</dd>

                <dt class="col-md-3">الهاتف</dt>
                <dd class="col-md-9">@Html.DisplayFor(model => model.OfficePhone)</dd>

                <dt class="col-md-3">المسؤول</dt>
                <dd class="col-md-9">@Html.DisplayFor(model => model.Representative.Name)</dd>
            </dl>
        </div>

        <div class="card-footer text-right">
            <a href="@Url.Action("Edit", "HajjOffice", new { id = Model.ID })" class="btn btn-success btn-lg px-4">تعديل</a>
            @Html.ActionLink("العودة الى القائمة", "Index", "HajjOffice", null, new { @class = "btn btn-secondary btn-lg px-4 ml-3" })
        </div>
    </div>
</div>

Base/Views/HajjOffice/Edit.cshtml
@model Base.Model1.HajjOffice

@{
    ViewBag.Title = "تعديل مكتب خدمة";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<br />
<br />
<br />
<br />

<div class="container mt-5">
   

    @using (Html.BeginForm())
    {
        <div class="card shadow-lg border-0">
            <div class="card-header bg-dark text-white">
                <h4 class="text-center">تعديل مكتب الخدمة  </h4>
            </div>
            <div class="card-body">

                <!-- Office Name Field -->
                <div class="form-group row">
                    @Html.LabelFor(model => model.OfficeName, "اسم المكتب", new { @class = "col-md-2 col-form-label text-right" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.OfficeName, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.OfficeName, "", new { @class = "text-danger" })
                    </div>
                </div>

                <!-- Office Phone Field -->
                <div class="form-group row">
                    @Html.LabelFor(model => model.OfficePhone, "رقم الهاتف", new { @class = "col-md-2 col-form-label text-right" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.OfficePhone, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.OfficePhone, "", new { @class = "text-danger" })
                    </div>
                </div>

                <!-- Office Representative Dropdown -->
                <div class="form-group row">
                    @Html.LabelFor(model => model.OfficeRepresentativeID, "المسؤول", new { @class = "col-md-2 col-form-label text-right" })
                    <div class="col-md-10">
                        @Html.DropDownList("OfficeRepresentativeID", ViewBag.RepresentativeList as SelectList, "حدد المسؤول", new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.OfficeRepresentativeID, "", new { @class = "text-danger" })
                    </div>
                </div>

                <!-- Submit Button -->
                <div class="form-group row mt-4">
                    <div class="col-md-10 offset-md-2 text-right">
                        <input type="submit" value="حفظ" class="btn btn-success btn-lg px-5" />
                        @Html.ActionLink("العودة", "Index", null, new { @class = "btn btn-secondary btn-lg px-5 ml-3" })
                    </div>
                </div>

            </div>
        </div>
    }
</div>

Base/Views/HajjOffice/Index.cshtml
@model IEnumerable<Base.Model1.HajjOffice>

@{
    ViewBag.Title = "قائمة مكاتب الخدمة";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container mt-5">
    <h2 class="text-center mb-4">مكاتب الخدمة</h2>

    <div class="text-right mb-3">
        <a href="@Url.Action("Create", "HajjOffice")" class="btn btn-primary btn-lg" style="display: inline-flex; align-items: center;" title="إنشاء مكتب خدمة">
            <i class="fas fa-plus"></i> 
        </a>
    </div>

    <!-- Your card and table code here -->
</div>

<!-- Make sure to include Font Awesome in your _Layout.cshtml or here -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">


<div class="card">
    <div class="card-header">
        <h4 class="text-center"> مكاتب الخدمة</h4>
    </div>
    <div class="card-body">
        <table class="table table-striped table-bordered">
            <thead class="thead-dark">
                <tr>
                    <th class="text-center">رقم المسلسل</th>
                    <th class="text-center">مكتب الخدمة</th>
                    <th class="text-center">هاتف المكتب</th>
                    <th class="text-center">المسؤول</th>
                    <th class="text-center">الإجراءات</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td class="text-center">@item.ID</td>
                        <td class="text-center">@item.OfficeName</td>
                        <td class="text-center">@item.OfficePhone</td>
                        <td class="text-center">@item.Representative?.Name</td>
                        <td class="text-center">
                            <a href="@Url.Action("Edit", new { id = item.ID })" class="btn btn-sm btn-warning" title="تعديل">
                                <i class="fas fa-edit"></i>
                            </a>
                            <a href="@Url.Action("Details", new { id = item.ID })" class="btn btn-sm btn-info" title="عرض">
                                <i class="fas fa-info-circle"></i>
                            </a>
                            <a href="@Url.Action("Delete", new { id = item.ID })" class="btn btn-sm btn-danger" title="حذف">
                                <i class="fas fa-trash-alt"></i>
                            </a>
                            <button type="button" class="btn btn-primary btn-sm" data-toggle="modal" data-target="#officeReqModal" onclick="loadOfficeReqForm(@item.ID) " title="ربط طلب">
                                <i class="fas fa-link"></i> 
                            </button>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>
</div>

<!-- Modal for creating Hajj Office request -->
<div class="modal fade" id="officeReqModal" tabindex="-1" role="dialog" aria-labelledby="officeReqModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body" id="modal-body-content">
                <!-- Partial view content will be loaded here dynamically -->
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <script type="text/javascript">
        function loadOfficeReqForm(officeId) {
            $.ajax({
                url: '@Url.Action("CreateOfficeReq", "HajjOffice")', // Adjust the URL to match your routing
                type: 'GET',
                data: { id: officeId }, // Send officeId to the server
                success: function (data) {
                    $('#modal-body-content').html(data); // Load the partial view into the modal body
                },
                error: function () {
                    alert('فشل في تحميل النموذج.');
                }
            });
        }
    </script>
}

Base/Views/HajjOffice/OfficeRequest.cshtml
@model Base.Model1.OfficeReq

@{
    ViewBag.Title = "ربط طلب بمكتب خدمة";
  
}


    @using (Html.BeginForm("CreateOfficeReq", "HajjOffice", FormMethod.Post, new { @id = "officeRequestForm", @class = "form-horizontal", role = "form" }))
    {
            <div class="card-header bg-dark text-white">
                <h4 class="text-center">إضافة طلب لمكتب خدمة</h4>
            </div>
            <div class="card-body">

                <div class="form-group row">
                    @Html.LabelFor(model => model.officeID, "مكتب خدمة", new { @class = "col-md-2 col-form-label text-right" })
                    <div class="col-md-10">
                        @Html.DropDownListFor(model => model.officeID, ViewBag.HajjOffices as SelectList, "أختار", new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.officeID, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group row">
                    @Html.LabelFor(model => model.reqID, "طلب حجاج", new { @class = "col-md-2 col-form-label text-right" })
                    <div class="col-md-10">
                        @Html.DropDownListFor(model => model.reqID, ViewBag.HajjRequests as SelectList, "أختار", new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.reqID, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group row">
                    @Html.LabelFor(model => model.Amount, "القيمة المطلوبة", new { @class = "col-md-2 col-form-label text-right" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(model => model.Amount, new { @class = "form-control", type = "number", placeholder = "أدخل القيمة" })
                        @Html.ValidationMessageFor(model => model.Amount, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group row">
                    @Html.LabelFor(model => model.ActualAmount, "القيمة الحقيقية", new { @class = "col-md-2 col-form-label text-right" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(model => model.ActualAmount, new { @class = "form-control", type = "number", placeholder = "أدخل القيمة الحقيقية" })
                        @Html.ValidationMessageFor(model => model.ActualAmount, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group row">
                    @Html.LabelFor(model => model.isBool, "نشط", new { @class = "col-md-2 col-form-label text-right" })
                    <div class="col-md-10">
                        @Html.CheckBoxFor(model => model.isBool, new { @class = "form-check-input" })
                        <label class="form-check-label"></label>
                        @Html.ValidationMessageFor(model => model.isBool, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group row mt-4">
                    <div class="col-md-10 offset-md-2 text-right">
                        <button type="button" onclick="submitOfficeRequest()" class="btn btn-success btn-lg px-5">حفظ</button>
                        <button type="button" class="btn btn-secondary btn-lg px-5 ml-3" data-dismiss="modal">إلغاء</button>
                    </div>
                </div>

            </div>
    }

@section Scripts {
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script>
        function submitOfficeRequest() {
            var form = $('#officeRequestForm');  // Target the form element
            var formData = form.serialize();     // Serialize form data

            $.ajax({
                type: 'POST',
                url: '@Url.Action("CreateOfficeReq", "HajjOffice")',  // Adjust the URL to match your routing
                data: formData,
                success: function (response) {
                    if (response.success) {
                        // Success: Hide the modal, show success alert, and reload the page
                        alert("تم حفظ الطلب بنجاح!");
                        $('#officeReqModal').modal('hide');
                        location.reload();  // Reload the page to refresh the list
                    } else {
                        // Validation failed: Reload the partial view with validation messages
                        $('#modal-body-content').html(response);
                    }
                },
                error: function () {
                    alert("حدث خطأ أثناء حفظ الطلب.");
                }
            });
        }
    </script>
}